apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Production Test
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: ProdEnv1
          artifact-id: 91ad5ca5-7579-4b4f-8cc1-0244b3f0cd44
          target-environment: ProdEnv