apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Production Test
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: ProdEnv1
          artifact-id: 7f5eabe4-bb37-4e37-b0b1-cb959e209d12
          target-environment: ProdEnv